config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get "home/about" => "homes#about"

  resources :books, only: [:index, :create, :show, :edit, :update, :destroy]
  resources :users, only: [:index, :update, :show, :edit]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  attachment :profile_image
  
  validates :name, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  
  
  
  # def after_sign_up_path_for(resource)
  #   user_path(current_user)
  # end
  
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
  
  

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  # def after_sign_up_path_for(resource)
  #   user_path(resource)
  # end
  
  before_action :authenticate_user!

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]="Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      # byebug
      @user = current_user
      @books = Book.all
      render "index"
    end
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end
  
  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
        render "edit"
    else
        redirect_to books_path
    end
  end
  
  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice]="Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice]="Book was successfully destroyed."
    redirect_to books_path
  end
  
  private
  def book_params
      params.require(:book).permit(:title, :body)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
  
  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!
  
  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    @books = Book.all
  end
  
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = Book.where(user_id: @user.id)
  end
  
  def edit
    @user = User.find(params[:id])
    if @user == current_user
        render "edit"
    else
      redirect_to user_path(current_user)
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "User info was successfully updated"
      redirect_to user_path(@user.id)
    else
      render "edit"
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<h2 class="">New book</h2>

<%= form_with model: book, local: true do |f| %>
  <div class="form-group">
    <%= f.label :title, class: "col-md-9" %>
    <%= f.text_field :title %>
  </div>

  <div class="form-group">
  	<%= f.label :opinion, class: "col-md-9" %>
    <%= f.text_area :body %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary col-md-6" %>
  </div>
<% end %>

app/views/books/_error.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <h3><%= model.errors.count %> errors prohibited this obj from being saved</h3>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class="error-message"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h1>Editing Book</h1>
      <%= render 'books/error', model: @book %>
      <%= render 'books/book', book: @book %>
    <div class="menu">
      <%= link_to "Show", book_path(@book) %>
        |
      <%= link_to "Back", books_path %>
    </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <%= render 'books/error', model: @book %>
		<div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <%= render 'books/book', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <table class="table">
        <h2>Books</h2>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <!--<th scope="row"></th>-->
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50,fallback: "no_image.jpg"%>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <%= render 'books/book', book: @newbook %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <thead>
          <tr>
            <td><%= attachment_image_tag @book.user, :profile_image, :fill, 50, 50,fallback: "no_image.jpg" %></td>
            <td><%= link_to @user.name, user_path(@user) %></td>
            <td><%= @book.title %></td>
            <td><%= @book.body %></td>
            <% if @book.user_id == current_user.id %>
              <td><%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
              <td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"}, class: "btn btn-sm btn-danger" %></td>
            <% end %>
            </tr>
        </thead>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="px-3 mx-auto">
      <h1>welcome to <span class="fas fa-book"></span><strong>Bookers</strong>  !!</h1>
    </div>
  </div>
</div>
  

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <span class="fas fa-book"></span><strong>Bookers</strong>  !!</h1>
    <!--<div class="col-md-6 col-md-offset-3">-->
    <!--<h1>welcome to Bookers!</h1>-->
    <p>In <span class="fas fa-book"></span><strong>Bookers,</strong></p>
    <p>you can share and exchange your opinions , inpressions , and emotions</p>
    <p>about various books!</p>
  <div class="btn-wrapper col-10 mx-auto">
    <div class="row">
    	<button class="btn btn-info btn-sm btn-block mb-3 sign_in"><%= link_to "Log in",new_user_session_path  %></button>
  	</div>
  	<div class="row">
    	<button class="btn btn-success btn-sm btn-block sign_up"><%= link_to "Sign Up",new_user_registration_path %></button>
  	</div>
	</div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Bookers2</title>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-default navbar-inverse">
    <div class="container-fluid">
    <%= link_to "Bookers", root_path, class: "navbar-brand" %>
      <ul class="navbar-nav nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to " Home", user_path(current_user.id), class: "fas fa-home nav-link text-light" %></li>
          <li><%= link_to " Users", users_path, class: "fas fa-users nav-link text-light" %></li>
          <li><%= link_to " Books", books_path, class: "fas fa-book-open nav-link text-light" %></li>
          <li><%= link_to " logout", destroy_user_session_path,  class: "fas fa-sign-out-alt nav-link text-light", method: :delete %></li>
        <% else %>
          <li><%= link_to " Home", root_path, class: "fas fa-home nav-link text-light" %></li>
          <li><%= link_to " About", home_about_path, class: "fas fa-link nav-link text-light" %></li>
          <li><%= link_to " sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %></li>
          <li><%= link_to " login", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %></li>
        <% end %>
      </ul>
    </div>
    </nav>
  </header>


  <div class="body">

    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
  </div>

 <%= yield %>


  <footer>
    <div class='container'>
      <div class='row'>
        <div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	  </div>
      </div>
    </div>
  </footer>
  </body>
</html>

app/views/users/_user.html.erb
<table class="table">
	<h2>User info</h2>
	<thead>
		<tr>
			<%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg"%>
		</tr>
	</thead>
	<tbody>
		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>
		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
	</tbody>
</table>
		<div class="row">
			<%= link_to "", edit_user_path(user), class:"btn btn-outline-secondary btn-block fas fa-user-cog" %>
		</div>

app/views/users/edit.html.erb
<h1>User info</h1>
<%= form_with model: @user, local: true do |f| %>
<%= render 'books/error', model: @user %>
  <div class="user-name">Name</div>
    <%= f.text_field :name %>
  <div class="user-edit-image">Image</div>
    <%= f.attachment_field :profile_image %>
  <div class="form-body">Introduction</div>
    <%= f.text_area :introduction %><br>
  <div class="upload">
    <%= f.submit " Update User" %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-3">
			<%= render 'users/user', user: @user %>
			<!--<h2>New Book</h2>-->
			<%= render 'books/book', book: @book %>
		</div>
		<div class="col-md-8 offset-md-1">
			<table class="table">
				<h2>Users</h2>
				<thead>
					<th>image</th>
					<th>name</th>
					<th></th>
				</thead>
				<tbody>
					<% @users.each do |user| %>
						<tr>
							<td><%= attachment_image_tag user, :profile_image, :fill, 50, 50,fallback: "no_image.jpg"%></td>
							<td><%= user.name %></td>
							<td><%= link_to "Show", "/users/#{user.id}" %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <!--<h2>New book</h2>-->
      <%= render 'books/book', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <table class="table book-index">
        <h2>Books</h2>
        <thead>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50,fallback: "no_image.jpg"%>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>